name: 'WebServer documentation'

on:
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  generate:
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Install Doxygen
        run: sudo apt-get install doxygen graphviz -y

      - name: Generate Doxygen Documentation
        run: doxygen Doxyfile

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: "gh-pages"
          folder: "documentation"